### ISSUE TITLE
Wordpress support?

### ISSUE THREAD

**Issue by IBMPortablePc** [bohdanbobrowski/blogspot2epub#6]
Congratulations on a great app!

Is support for Wordpress likely in the near future?

**Comment by EdigitalmediaG** [comment]
441grados.mx

**Comment by EdigitalmediaG** [comment]
Https://441grados.mx

**Comment by bohdanbobrowski** [comment]
Yes, for sure Wordpress is on my "roadmap" for this app, but can't say when I'll implement it.
